// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB75bKDtPPnuCdM7Aw4ZN-JIx7roFQre38',
    appId: '1:338526986915:web:ac315e961356d12fa49516',
    messagingSenderId: '338526986915',
    projectId: 'appito-b822d',
    authDomain: 'appito-b822d.firebaseapp.com',
    storageBucket: 'appito-b822d.appspot.com',
    measurementId: 'G-VTNDZRPERH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVXhGFAjUqIJ0RQ29RnTXT_rDOrnAv-AA',
    appId: '1:338526986915:android:d23c7cd33bdeb55ba49516',
    messagingSenderId: '338526986915',
    projectId: 'appito-b822d',
    storageBucket: 'appito-b822d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOs3QYRIhkAfyuqK5x2zndeokhcdqU_KE',
    appId: '1:338526986915:ios:198f40137ab61197a49516',
    messagingSenderId: '338526986915',
    projectId: 'appito-b822d',
    storageBucket: 'appito-b822d.appspot.com',
    iosClientId: '338526986915-m7kfqqcq7en4qabib4nconsb1fpi2qlo.apps.googleusercontent.com',
    iosBundleId: 'com.nucleus.appito',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB75bKDtPPnuCdM7Aw4ZN-JIx7roFQre38',
    appId: '1:338526986915:web:cd8f726020a9ddf9a49516',
    messagingSenderId: '338526986915',
    projectId: 'appito-b822d',
    authDomain: 'appito-b822d.firebaseapp.com',
    storageBucket: 'appito-b822d.appspot.com',
    measurementId: 'G-JVE6DW1EHT',
  );
}
