name: flutter_boilerplate
description: Flutter boilerplate project for a quick start
publish_to: 'none' 
version: 1.0.0+1


environment:
  sdk: ">=2.13.4 <3.0.0"
  flutter: ">=2.2.3"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  catcher: ^0.6.8
  location: ^4.2.3
  provider: ^6.0.1
  expandable: ^5.0.1
  liquid_swipe: ^2.1.0
  url_launcher: ^6.0.3
  octo_image: ^1.0.0+1
  fluttertoast: ^8.0.6
  flutter_bloc: ^7.3.0
  image_cropper: ^1.4.1
  photo_manager: ^1.3.1
  image_picker: ^0.8.1+3
  dotted_border: ^2.0.0+1
  carousel_slider: ^4.0.0
  pull_to_refresh: ^2.0.0
  webview_flutter: ^2.0.12
  rest_api_client: ^1.0.19
  flutter_typeahead: ^3.1.3
  connectivity_plus: ^1.0.5
  storage_repository: ^1.0.7
  permission_handler: ^8.1.2
  google_maps_flutter: ^2.0.6
  cached_network_image: ^3.0.0
  google_maps_webservice: ^0.0.20-nullsafety.5


dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
  bloc_test: ^8.2.0
  flutter_flavorizr: ^2.0.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter


flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
  
  instructions:
    - android:androidManifest
    - flutter:flavors
    - ios:xcconfig
    - ios:buildTargets
    - ios:schema
    - ios:plist
    - ios:dummyAssets
    - ios:launchScreen
  
  flavors:
    production:
      app:
        name: "FlutterBoilerplate"
      android:
        applicationId: "com.ito.flutter_boilerplate"
      ios:
        bundleId: "com.ito.flutter_boilerplate"

    staging:
      app:
        name: "FlutterBoilerplate Staging"
      android:
        applicationId: "com.ito.flutter_boilerplateStaging"
      ios:
        bundleId: "com.ito.flutter_boilerplateStaging"

    evaluation:
      app:
        name: "FlutterBoilerplate Evaluation"
      android:
        applicationId: "com.ito.flutter_boilerplateEvaluation"
      ios:
        bundleId: "com.ito.flutter_boilerplateEvaluation"

    development:
      app:
        name: "FlutterBoilerplate Development"
      android:
        applicationId: "com.ito.flutter_boilerplateDevelopment"
      ios:
        bundleId: "com.ito.flutter_boilerplateDevelopment"


flutter:
  uses-material-design: true
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/icons/AppIcons.ttf
    - family: MavenPro Black
      fonts:
        - asset: assets/fonts/MavenPro-Black.ttf
    - family: MavenPro Bold
      fonts:
        - asset: assets/fonts/MavenPro-Bold.ttf
    - family: MavenPro ExtraBold
      fonts:
        - asset: assets/fonts/MavenPro-ExtraBold.ttf
    - family: MavenPro Medium
      fonts:
        - asset: assets/fonts/MavenPro-Medium.ttf
    - family: MavenPro Regular
      fonts:
        - asset: assets/fonts/MavenPro-Regular.ttf
    - family: MavenPro SemiBold
      fonts:
        - asset: assets/fonts/MavenPro-SemiBold.ttf
        

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/images/application/
    - assets/images/flags/
    - assets/images/map/
    - assets/images/onboarding/
    - assets/images/placeholders/
