// import 'package:flutter_boilerplate/_all.dart';

// class AppIcons {
//   AppIcons._();

//   static const _kFontFam = 'AppIcons';
//   static const String? _kFontPkg = null;

//   static const IconData arrowLeft = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData arrowRight = Icons.chevron_right;
//   static const IconData closeCircle = Icons.close;
//   static const IconData flipCamera = Icons.flip_camera_android_outlined;
//   static const IconData list = Icons.list_alt;
//   static const IconData lock = Icons.lock;
//   static const IconData logout = Icons.logout;
//   static const IconData camera = Icons.camera;
//   static const IconData image = Icons.image;
//   static const IconData more = Icons.more_horiz;
//   static const IconData compareList = Icons.compare;
//   static const IconData aboutUs = Icons.verified_user;
//   static const IconData faq = Icons.chat_bubble;
//   static const IconData privacyPolicy = Icons.shield;
//   static const IconData termsAndConditions = Icons.list;

//   static const IconData walking = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData worldwide = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData stripe = IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData ticket = IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData ticket1 = IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData ticket2 = IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData user = IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData qr = IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData search = IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData share = IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData shareTicket = IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData star = IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData star1 = IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData filter = IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData guest = IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData hearth = IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData hearth1 = IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData home = IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData dropPin = IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData events = IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData expand = IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData calendar = IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cart = IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData categories = IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData chat = IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData chekbox = IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData chekbox2 = IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData close1 = IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData marker = IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData menu = IconData(0xe91d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData mesages = IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData back = IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bookmark = IconData(0xe920, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bookmark1 = IconData(0xe921, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData plus = IconData(0xea0a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData minus = IconData(0xea0b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
// }

import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData map = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shareTicket = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  //static const IconData back = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData closeChip = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dotsMenuVertical = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dropPin = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData starEmpty = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket1 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData starFilled = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compare = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chekbox = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket2 = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket3 = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chekboxActive = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userImage = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hearthFilled = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radioCheked = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData categories = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radio = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData switchCamera = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData success = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dotsMenuHorizontal = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData termsAndConditions = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hearth = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData walking = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData template = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qrCode = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronDown = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock2 = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mapPin = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData event = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData marker = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userInfo = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stripe = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signOut = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expand = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faq = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendarPlus = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronRight = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData imageGallery = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronUp = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData creditCard = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin1 = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronLeft = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
